GET http://127.0.0.1:8000/api/persona?orderby=id&q=&limit=3&page=1
Accept: application/json
Authorization: Bearer 64|L0YTpuyw0qvhXrcudIYQf9trDOlNGqbFhZigqARG

### Guardar Persona
POST http://127.0.0.1:8000/api/persona
Accept: application/json
Authorization: Bearer 7|KQ1o1sjjsk0ULtA3MdKUpvO5ktsUpIMpuQYBx9tD
Content-Type: application/json

{
    "nombres": "Ana",
    "apellidos": "Sanchez",
    "ci_nit": "444444",
    "direccion": "Av ABC",
    "telefono": "678678"
}


### asignacion de materias
POST https://sis-academico.herokuapp.com/api/persona/2/asignacion-materias
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|3bncikXVO5Iri3mlxF9WzM607jHhyNdNCuX1s1PK

{
    "materias": [4],
    "gestion": 1,
    "rol": "Estudiante"
}

